# On each release : this workflow will build a container with JIB and pulish it to GitHub Packages

name: JIB container publish

on:
  release:
    types: [created]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Username to login to registry
  USERNAME: ${{ github.actor }}
  # Password to login to registry
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:

    runs-on: ubuntu-latest
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build JIB container and publish to GitHub Packages
      run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build \
      -Djib.to.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
      -Djib.to.auth.username=${{ env.USERNAME }} \
      -Djib.to.auth.password=${{ env.PASSWORD }}
